[http.middlewares.middlewares-local-ip.ipWhiteList]
sourceRange = ["127.0.0.1/32", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12"]

[http.middlewares.middlewares-ipwhitelist.ipWhiteList]
sourceRange = [
  "173.245.48.0/20",
  "103.21.244.0/22",
  "103.22.200.0/22",
  "103.31.4.0/22",
  "141.101.64.0/18",
  "108.162.192.0/18",
  "190.93.240.0/20",
  "188.114.96.0/20",
  "197.234.240.0/22",
  "198.41.128.0/17",
  "162.158.0.0/15",
  "104.16.0.0/13",
  "104.24.0.0/14",
  "172.64.0.0/13",
  "131.0.72.0/22",
]

[http.middlewares.middlewares-rate-limit.rateLimit]
average = 100
burst = 50

[http.middlewares.middlewares-https-redirectscheme.redirectScheme]
scheme = "https"
permanent = true

[http.middlewares.middlewares-compress]
compress = {}

[http.middlewares.middlewares-authelia.forwardAuth]
address = "http://authelia:9091/api/verify?rd=https://auth.<site.domain>"
trustForwardHeader = true
authResponseHeaders = ["Remote-User", "Remote-Groups"]

[http.middlewares.middlewares-control-allow-methods.headers]
accessControlAllowMethods = ["GET", "OPTIONS", "PUT"]
accessControlMaxAge = 100

[tcp.middlewares.middlewares-tcp-local-ip.ipWhiteList]
sourceRange = ["127.0.0.1/32", "10.0.0.0/8", "192.168.0.0/16", "172.16.0.0/12"]
